# Generated by Django 3.1.3 on 2021-05-07 22:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=16)),
                ('IP_ADDR', models.GenericIPAddressField()),
                ('URL', models.URLField(null=True)),
                ('FUNC_NAME', models.CharField(max_length=64)),
                ('DATE', models.DateTimeField()),
            ],
            managers=[
                ('log', django.db.models.manager.Manager()),
            ],
        ),
    ]
