# Generated by Django 3.2.3 on 2021-05-19 09:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customauth', '0024_alter_sessions_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='customauth.usr')),
            ],
            options={
                'db_table': 'AArooms',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
