# Generated by Django 3.2.3 on 2021-05-19 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='userrooms',
            name='room_name',
        ),
        migrations.AddField(
            model_name='userrooms',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.room'),
            preserve_default=False,
        ),
    ]
