# Generated by Django 3.2.3 on 2021-05-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210519_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chat_log',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
