# Generated by Django 3.2.3 on 2021-05-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_chat_log'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='AAroom',
        ),
        migrations.AlterModelTable(
            name='userrooms',
            table='AAuserrooms',
        ),
    ]
