# Generated by Django 3.2.3 on 2021-05-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210519_1730'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='AArooms',
        ),
    ]
