# Generated by Django 3.1.3 on 2021-05-12 21:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0004_auto_20210513_0003'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usr',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
