# Generated by Django 3.2.3 on 2021-05-13 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0011_alter_sessions_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 23, 11, 47, 370423)),
        ),
        migrations.AlterModelTable(
            name='sessions',
            table='AAsession',
        ),
        migrations.AlterModelTable(
            name='usr',
            table='AAuser',
        ),
    ]
