# Generated by Django 3.1.3 on 2021-05-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_auto_20210513_0000'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usr',
            table='AAuser',
        ),
    ]
