# Generated by Django 3.1.3 on 2021-05-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0005_auto_20210513_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('session_key', models.CharField(default='', max_length=24, primary_key=True, serialize=False)),
                ('session_data', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='usr',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usr',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
