# Generated by Django 3.1.3 on 2021-05-13 03:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0007_auto_20210513_0525'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sessions',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
