# Generated by Django 3.2.3 on 2021-05-13 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0008_auto_20210513_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 23, 9, 34, 519428)),
        ),
    ]
