# Generated by Django 3.2.3 on 2021-05-13 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0012_auto_20210513_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 23, 12, 0, 621755)),
        ),
    ]
