# Generated by Django 3.2.3 on 2021-05-16 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0018_alter_sessions_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 7, 49, 24, 322393)),
        ),
        migrations.AlterField(
            model_name='usr',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
