# Generated by Django 3.2.3 on 2021-05-16 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0019_auto_20210516_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 8, 39, 42, 865836)),
        ),
    ]
